### ISSUE TITLE
Adding Luckysheet to project by ES6 imports. 

### ISSUE THREAD

**Issue by pawelkociubinski** [mengshukeji/Luckysheet#227] opened 2020-11-16 12:20 UTC
Hello, I have a question for the makers of Luckysheet. In the current react.js project, we want to use Luckysheet, but we cannot use the CDN option due to privacy and security policy. Do you guys plan to improve support for the NPM package of this library? 

Right now, I tried the option with require:
```
const jquery = require("jquery")
const w = window as any
w.$ = jquery

require("jquery-mousewheel")
require("luckysheet/dist/plugins/css/pluginsCss.css")
require("luckysheet/dist/plugins/plugins.css")
require("luckysheet/dist/css/luckysheet.css")
require("luckysheet/dist/assets/iconfont/iconfont.css")
require("luckysheet/dist/plugins/js/plugin.js")
const luckysheet = require("luckysheet/dist/luckysheet.umd")
```
As you can see, I have to install jquery separately to display Luckysheet (Importing of plugin.js in this way doesn't solve a problem with binding $ to window object). The biggest problem is with Luckyexcel which don't want to be imported into the component in any way:D

If you are not planning to work on this improvement, is it possible that I could prepare it for you?

**Comment by mengshukeji** [comment] 2020-11-18 04:06
Thank you very much for your attention. We have planned to improve the problem of npm.

We did not list the tasks in the issues before, now you can view all the project issues through the issues label [`project`](https://github.com/mengshukeji/Luckysheet/issues?q=is%3Aopen+is%3Aissue+label%3Aproject)

Because the repair of this issue requires continuity and integrity, we invited @zhangchen915 to repair it.
Especially these two issues https://github.com/mengshukeji/Luckysheet/issues/239 and https://github.com/mengshukeji/Luckysheet/issues/240 focuses on solving npm issues, you can continue to follow our progress and make suggestions.

**Comment by mengshukeji** [comment] 2020-11-18 04:06
Duplicate of #240

**Closed** 2020-12-31 07:09 UTC
