### ISSUE TITLE
Two sheets in one page

### ISSUE THREAD

**Issue by yerycs** [mengshukeji/Luckysheet#131] opened 2020-10-27 20:21 UTC
![1](https://user-images.githubusercontent.com/53403186/97357560-f22b7600-18d4-11eb-9552-194e0ea72660.png)
Two sheets in one page are not working well.
一頁中的兩張紙效果不佳。

**Comment by yerycs** [comment] 2020-10-28 02:56
I think it is critical issue.
This module just finds static id and implement. Need to refer user-defined id or class as parent element.
Any idea to fix issue?

**Comment by mengshukeji** [comment] 2020-10-28 03:53
Duplicate of #97，多实例的问题

**Closed** 2020-10-28 03:54 UTC

**Comment by iiyuwan** [comment] 2021-06-30 13:39
请问多实例的问题怎么样啦？
