### ISSUE TITLE
Is there a possibility to add a new item to the right click menu?

### ISSUE THREAD

**Issue by alankoibagarov** [mengshukeji/Luckysheet#443] opened 2021-01-06 09:41 UTC
Hi, 

I just wanted to add a new item with my own custom method and it seems like i can only hide/show existing ones with cellRightClickConfig object like in the code below from here [https://mengshukeji.github.io/LuckysheetDocs/guide/config.html#cellrightclickconfig](url) :

`
{
	copy: false, // copy
	copyAs: false, // copy as
	paste: false, // paste
	insertRow: false, // insert row
	insertColumn: false, // insert column
	deleteRow: false, // delete the selected row
	deleteColumn: false, // delete the selected column
	deleteCell: false, // delete cell
	hideRow: false, // hide the selected row and display the selected row
	hideColumn: false, // hide the selected column and display the selected column
	rowHeight: false, // row height
	columnWidth: false, // column width
	clear: false, // clear content
	matrix: false, // matrix operation selection
	sort: false, // sort selection
	filter: false, // filter selection
	chart: false, // chart generation
	image: false, // insert picture
	link: false, // insert link
	data: false, // data verification
	cellFormat: false // Set cell format
}
`

Is it possible to do so in current version of the package?

**Comment by mengshukeji** [comment] 2021-01-18 03:15
For now,you can add some html template string to `src/controllers/constant.js`, and add custom listening events in `src/controllers/hander.js`。


Duplicate of #242

**Closed by mengshukeji** 2021-01-18 03:15 UTC
