### ISSUE TITLE
[Feature request]Optimization: The data is too large

### ISSUE THREAD

**Issue by Dushusir** [mengshukeji/Luckysheet#406] opened 2020-12-28 05:45 UTC
**Is your feature request related to a problem? Please describe.**
An excel document (200K) with more than 1,000 rows, after being stored as a luckysheet, the db field reached more than 13 million characters (more than 60 times enlarged).

**Describe the solution you'd like**
The style of each cell is stored separately and takes up a lot of space. Consider separating repeated cell configurations

问题：
一个1000多行的excel文档(200K)，存储成luckysheet后，db字段达到了1300多万个字符(扩大了60多倍)。
解决计划：
每个单元格的样式都是单独存储的，占用了很大空间。考虑分离重复的单元格配置

**Comment by mengshukeji** [comment] 2020-12-31 06:01
Duplicate of #418

**Closed by mengshukeji** 2020-12-31 06:01 UTC
Labels: enhancement, important
